version: "3"

services:
 
  popi:
    container_name: bot
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  default:
    external:
      name: popi-network